import { createClient } from "@/lib/supabase/server"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Trophy } from "lucide-react"

export default async function MeritPage() {
  const supabase = await createClient()

  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) return null

  // Get user's merit evaluations
  const { data: meritEvaluations } = await supabase
    .from("merit_evaluations")
    .select("*")
    .eq("student_id", user.id)
    .order("evaluation_date", { ascending: false })

  // Get approved submissions for current calculation
  const { data: approvedSubmissions } = await supabase
    .from("submissions")
    .select("points_awarded")
    .eq("student_id", user.id)
    .eq("status", "approved")

  const currentPoints = approvedSubmissions?.reduce((sum, s) => sum + (s.points_awarded || 0), 0) || 0

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Merit Ranking</h1>
        <p className="text-muted-foreground">View your merit evaluation and ranking</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Trophy className="h-5 w-5" />
            Current Merit Points
          </CardTitle>
          <CardDescription>Based on approved achievements</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="text-4xl font-bold">{currentPoints} points</div>
        </CardContent>
      </Card>

      {meritEvaluations && meritEvaluations.length > 0 ? (
        <div className="space-y-4">
          <h2 className="text-xl font-semibold">Evaluation History</h2>
          {meritEvaluations.map((evaluation: any) => (
            <Card key={evaluation.id}>
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div>
                    <CardTitle>
                      {evaluation.academic_year} - {evaluation.semester}
                    </CardTitle>
                    <CardDescription>
                      Evaluated on {new Date(evaluation.evaluation_date).toLocaleDateString()}
                    </CardDescription>
                  </div>
                  {evaluation.rank && <Badge variant="secondary">Rank #{evaluation.rank}</Badge>}
                </div>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4 md:grid-cols-3">
                  <div>
                    <p className="text-sm text-muted-foreground">Total Points</p>
                    <p className="text-2xl font-bold">{evaluation.total_points}</p>
                  </div>
                  {evaluation.rank && (
                    <div>
                      <p className="text-sm text-muted-foreground">Rank</p>
                      <p className="text-2xl font-bold">#{evaluation.rank}</p>
                    </div>
                  )}
                  {evaluation.percentile && (
                    <div>
                      <p className="text-sm text-muted-foreground">Percentile</p>
                      <p className="text-2xl font-bold">{evaluation.percentile}%</p>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      ) : (
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-12">
            <p className="text-muted-foreground">No merit evaluations yet</p>
            <p className="text-sm text-muted-foreground mt-2">
              Merit rankings will be generated by administrators periodically
            </p>
          </CardContent>
        </Card>
      )}
    </div>
  )
}
